"use client";
import {useEffect,useState} from "react";
import {BedDouble,Building2,ClipboardList,Download,UsersRound} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {getFacilities,getBedBoard,getRoster,getReferralQueue,createGovernanceExport} from "@/lib/api";
import {getToken} from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/admin",label:"Operations",icon:Building2},{href:"/network",label:"Care network",icon:BedDouble},{href:"/platform",label:"Platform",icon:ClipboardList},{href:"/intelligence",label:"Intelligence",icon:UsersRound}];
export default function Network(){const [fac,setFac]=useState<any[]>([]);const [beds,setBeds]=useState<any[]>([]);const [roster,setRoster]=useState<any[]>([]);const [queue,setQueue]=useState<any[]>([]);const [exported,setExported]=useState<any>(null);useEffect(()=>{const t=getToken();if(t){getFacilities(t).then(setFac);getBedBoard(t).then(setBeds);getRoster(t).then(setRoster);getReferralQueue(t).then(setQueue)}},[]);async function exp(){const t=getToken();if(t)setExported(await createGovernanceExport(t))}return <ProtectedDashboard requiredRole="admin">{(u,l)=><AppShell user={u} logout={l} nav={nav} active="/network" title="Care network" subtitle="Multi-facility operations, beds, workforce and referral flow."><div className="opsStats"><article><Building2/><b>{fac.length}</b><span>Facilities</span></article><article><BedDouble/><b>{beds.reduce((a,b)=>a+b.available,0)}</b><span>Beds available</span></article><article><UsersRound/><b>{roster.filter(x=>x.status==="on_shift").length}</b><span>On shift</span></article><article><ClipboardList/><b>{queue.filter(x=>x.status!=="booked").length}</b><span>Referral queue</span></article></div><div className="grid"><section className="card span2"><h2>Bed command board</h2><div className="bedBoard">{beds.map(b=><article key={b.id}><div><b>{b.ward}</b><span>{b.occupied}/{b.total} occupied</span></div><div className="loadBar"><i style={{width:`${b.occupancy}%`}}/></div><strong>{b.available} free</strong></article>)}</div></section><section className="card"><h2>Governance</h2><p>Prepare a governed operational export for authorised review.</p><button className="secondaryButton" onClick={exp}><Download size={16}/> Create export</button>{exported&&<div className="successBox">Export #{exported.id} · {exported.status}</div>}</section><section className="card span3"><h2>Referral flow</h2><div className="queueTable">{queue.map(q=><article key={q.id}><b>{q.specialty}</b><span>{q.urgency}</span><span>{q.status}</span><strong>{q.age_hours}h</strong></article>)}</div></section></div></AppShell>}</ProtectedDashboard>}
