"use client";
import {useEffect,useMemo,useState} from "react";
import {Activity,AlertTriangle,ClipboardList,FileSignature,FlaskConical,LayoutDashboard,MessagesSquare,Pill,Route,ShieldCheck,Stethoscope,Users,Video,Watch} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {checkMedicationInteractions,createAdvancedLab,createAdvancedReferral,createClinicalLetter,createPrescription,createRiskAssessment,getAdvancedPatientSummary,getClinicalPatients,getLatestRisk,signClinicalLetter,type AdvancedPatientSummary,type ClinicalPatient,type InteractionFinding,type RiskAssessment} from "@/lib/api";
import {getToken} from "@/lib/auth";

const nav:NavItem[]=[
 {href:"/dashboard/doctor",label:"Clinical dashboard",icon:LayoutDashboard},
 {href:"/patients",label:"Patient records",icon:Users},
 {href:"/clinical-actions",label:"Care actions",icon:Stethoscope,badge:"New"},
 {href:"/video",label:"Video consultations",icon:Video},
 {href:"/messages",label:"Secure messages",icon:MessagesSquare},
 {href:"/watch",label:"Remote monitoring",icon:Watch},
];

type Tab="prescribe"|"labs"|"referral"|"risk"|"letter";
export default function ClinicalActionsPage(){
 const[patients,setPatients]=useState<ClinicalPatient[]>([]);const[patientId,setPatientId]=useState<number|0>(0);const[summary,setSummary]=useState<AdvancedPatientSummary|null>(null);const[tab,setTab]=useState<Tab>("prescribe");const[msg,setMsg]=useState("");const[busy,setBusy]=useState(false);const[interactions,setInteractions]=useState<InteractionFinding[]>([]);const[risk,setRisk]=useState<RiskAssessment|null>(null);const[lastLetter,setLastLetter]=useState<any>(null);
 const token=()=>getToken()||"";
 useEffect(()=>{const t=token();if(!t)return;getClinicalPatients(t).then(p=>{setPatients(p);if(p[0])setPatientId(p[0].patient_id)}).catch(()=>{})},[]);
 useEffect(()=>{const t=token();if(!t||!patientId)return;Promise.all([getAdvancedPatientSummary(t,patientId),getLatestRisk(t,patientId)]).then(([s,r])=>{setSummary(s);setRisk(r)}).catch(()=>{})},[patientId]);
 const meds=useMemo(()=>summary?.medications?.map((m:any)=>m.name)??[],[summary]);
 async function act(fn:()=>Promise<any>,success:string){setBusy(true);setMsg("");try{await fn();setMsg(success);if(patientId)setSummary(await getAdvancedPatientSummary(token(),patientId))}catch(e:any){setMsg(e?.message||"Action could not be completed") }finally{setBusy(false)}}
 async function runInteraction(){try{const r=await checkMedicationInteractions(token(),meds);setInteractions(r.findings);setMsg(r.findings.length?`${r.findings.length} interaction review item${r.findings.length===1?"":"s"} found.`:"No configured interaction rules were triggered.")}catch(e:any){setMsg(e?.message||"Could not run interaction review")}}
 return <ProtectedDashboard requiredRole="doctor">{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/clinical-actions" title="Care actions" subtitle="Prescribe, request investigations, refer, assess coordination risk and produce signed clinical correspondence from one workspace.">
 <div className="clinicalActionHero"><div><span className="eyebrow"><ShieldCheck size={14}/> CLINICIAN CONTROL SURFACE</span><h2>From decision to action without losing context.</h2><p>Select a patient once, then work across medicines, diagnostics, referrals, risk and correspondence.</p></div><label className="patientPicker"><span>Current patient</span><select value={patientId} onChange={e=>setPatientId(Number(e.target.value))}>{patients.map(p=><option key={p.patient_id} value={p.patient_id}>{p.full_name}</option>)}</select></label></div>
 <div className="contextStrip"><article><b>{summary?.medications?.length??0}</b><span>Active medicines</span></article><article><b>{summary?.labs?.length??0}</b><span>Recent labs</span></article><article><b>{summary?.referrals?.length??0}</b><span>Referrals</span></article><article className={`riskBand ${risk?.band||"low"}`}><b>{risk?.score??18}</b><span>{risk?.band||"low"} coordination risk</span></article></div>
 <div className="careTabs">{([['prescribe','Prescription',Pill],['labs','Lab request',FlaskConical],['referral','Referral',Route],['risk','Risk review',Activity],['letter','Clinical letter',FileSignature]] as const).map(([k,l,I])=><button key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}><I size={16}/>{l}</button>)}</div>
 {msg&&<div className="inlineNotice">{msg}</div>}
 {tab==="prescribe"&&<section className="card actionPanel"><div className="cardTop"><h2>Electronic prescription</h2><Pill size={18}/></div><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>createPrescription(token(),{patient_id:patientId,name:String(f.get('name')),dose:String(f.get('dose')),schedule:String(f.get('schedule')),instructions:String(f.get('instructions')),next_due:String(f.get('next_due'))}),"Prescription added to the patient medication plan.")}} className="clinicalForm"><label><span>Medication</span><input name="name" placeholder="e.g. Amlodipine" required/></label><label><span>Dose</span><input name="dose" placeholder="5 mg" required/></label><label><span>Schedule</span><input name="schedule" placeholder="Once daily" required/></label><label><span>Next dose</span><input name="next_due" placeholder="20:00"/></label><label className="span2"><span>Instructions</span><textarea name="instructions" placeholder="Clinical directions and counselling points"/></label><div className="span2 inlineActions"><button className="btn primary" disabled={!patientId||busy}><Pill size={15}/> Prescribe</button><button type="button" className="btn outline" onClick={runInteraction} disabled={!meds.length}><AlertTriangle size={15}/> Review interactions</button></div></form>{interactions.length>0&&<div className="interactionList">{interactions.map((x,i)=><article key={i}><em className={x.severity}>{x.severity}</em><b>{x.medications.join(" + ")}</b><p>{x.detail}</p></article>)}</div>}</section>}
 {tab==="labs"&&<section className="card actionPanel"><div className="cardTop"><h2>Investigation request</h2><FlaskConical size={18}/></div><form className="clinicalForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>createAdvancedLab(token(),{patient_id:patientId,test_name:String(f.get('test'))}),"Laboratory request sent.")}}><label className="span2"><span>Test or panel</span><input name="test" placeholder="e.g. Complete blood count" required/></label><button className="btn primary" disabled={!patientId||busy}><FlaskConical size={15}/> Request investigation</button></form><div className="timelineCompact">{summary?.labs?.slice(0,5).map((l:any)=><div key={l.id}><i/><span><b>{l.test_name}</b><small>{l.status}{l.result_value?` · ${l.result_value}`:""}</small></span></div>)}</div></section>}
 {tab==="referral"&&<section className="card actionPanel"><div className="cardTop"><h2>Specialist referral</h2><Route size={18}/></div><form className="clinicalForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>createAdvancedReferral(token(),{patient_id:patientId,specialty:String(f.get('specialty')),destination:String(f.get('destination')),reason:String(f.get('reason')),urgency:String(f.get('urgency'))}),"Referral created and added to the care pathway.")}}><label><span>Speciality</span><input name="specialty" placeholder="Neurology" required/></label><label><span>Urgency</span><select name="urgency"><option>routine</option><option>urgent</option><option>priority</option></select></label><label className="span2"><span>Destination</span><input name="destination" defaultValue="MediLink specialist network"/></label><label className="span2"><span>Clinical reason</span><textarea name="reason" required placeholder="Reason for referral and relevant findings"/></label><button className="btn primary" disabled={!patientId||busy}><Route size={15}/> Send referral</button></form></section>}
 {tab==="risk"&&<section className="card actionPanel"><div className="riskHeader"><div><span className={`riskBadge ${risk?.band||"low"}`}>{risk?.band||"low"}</span><h2>Care-coordination risk</h2><p>{risk?.rationale}</p></div><div className="riskScore"><strong>{risk?.score??18}</strong><span>/100</span></div></div><form className="riskSliders" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{const r=await createRiskAssessment(token(),{patient_id:patientId,symptom_burden:Number(f.get('symptom_burden')),recent_unplanned_care:Number(f.get('recent_unplanned_care')),medication_complexity:Number(f.get('medication_complexity')),monitoring_alerts:Number(f.get('monitoring_alerts')),missed_followups:Number(f.get('missed_followups'))});setRisk(r)},"Risk review saved.")}}>{[['symptom_burden','Symptom burden'],['recent_unplanned_care','Recent unplanned care'],['medication_complexity','Medication complexity'],['monitoring_alerts','Monitoring alerts'],['missed_followups','Missed follow-ups']].map(([n,l])=><label key={n}><span>{l}</span><select name={n} defaultValue="1"><option value="0">None</option><option value="1">Low</option><option value="2">Moderate</option><option value="3">High</option></select></label>)}<button className="btn primary span2" disabled={!patientId||busy}><Activity size={15}/> Recalculate care risk</button></form></section>}
 {tab==="letter"&&<section className="card actionPanel"><div className="cardTop"><h2>Clinical correspondence</h2><FileSignature size={18}/></div><form className="clinicalForm" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);createClinicalLetter(token(),{patient_id:patientId,title:String(f.get('title')),recipient:String(f.get('recipient')),body:String(f.get('body'))}).then(x=>{setLastLetter(x);setMsg("Clinical letter saved as draft.")}).catch((e:any)=>setMsg(e?.message||"Could not create letter")).finally(()=>setBusy(false))}}><label><span>Title</span><input name="title" defaultValue="Clinical care letter"/></label><label><span>Recipient</span><input name="recipient" defaultValue="Care team"/></label><label className="span2"><span>Letter</span><textarea name="body" rows={9} placeholder="Clinical summary, findings, plan and requested action" required/></label><button className="btn primary" disabled={!patientId||busy}><ClipboardList size={15}/> Save letter</button>{lastLetter&&<button type="button" className="btn outline" onClick={()=>act(async()=>{const x=await signClinicalLetter(token(),lastLetter.id);setLastLetter(x)},"Letter signed and locked for export.")}><FileSignature size={15}/> Sign letter</button>}</form>{lastLetter?.status==="signed"&&<p className="muted small">Signed clinical correspondence is ready for PDF export from API endpoint <code>/api/v1/advanced/letters/{lastLetter.id}/pdf</code>.</p>}</section>}
 </AppShell>}</ProtectedDashboard>
}
