import Link from "next/link";
import { BrainCircuit, CalendarCheck, FileHeart, HeartPulse, LockKeyhole, MessagesSquare, ShieldCheck, Sparkles, Stethoscope, Video, Watch } from "lucide-react";
import BrandLogo from "@/components/BrandLogo";
import ThemeToggle from "@/components/ThemeToggle";
import CareCarousel from "@/components/CareCarousel";

const features=[
 {icon:BrainCircuit,title:"AI Health Assistant",text:"Record-aware  Copilot, speciality routing and transparent model confidence.",status:"Live"},
 {icon:Video,title:"Secure video care",text:"Authenticated room creation with browser camera/mic controls and WebRTC-ready transport.",status:"Beta"},
 {icon:Watch,title:"MediLink Watch",text:" real-time heart rate, SpO₂, temperature, blood pressure and activity streams.",status:"Live"},
 {icon:FileHeart,title:"Health records",text:"Labs, medications and a longitudinal care timeline using  patient data.",status:"Live"},
 {icon:MessagesSquare,title:"Secure messaging",text:"Care-team conversations in a dedicated protected workspace.",status:""},
 {icon:ShieldCheck,title:"Emergency support",text:"Fast access to emergency actions without asking AI to make the emergency decision.",status:"Live"},
];

export default function Home(){return <main className="site">
 <header className="siteNav"><Link href="/" className="brand"><BrandLogo/></Link><nav className="siteLinks"><a href="#platform">Platform</a><a href="#intelligence">AI</a><a href="#connected">Connected health</a><a href="#security">Security</a></nav><div className="siteActions"><ThemeToggle/><Link className="btn ghost" href="/login">Sign in</Link><Link className="btn primary" href="/register">Get started</Link></div></header>
 <section className="homeHero"><div className="homeHeroCopy"><span className="chip"><Sparkles size={14}/> Healthcare, connected intelligently</span><h1>Care that moves with you.</h1><p>MediLink unifies doctors, appointments, connected vitals, health records and responsible AI in one modern healthcare workspace.</p><div className="heroButtons"><Link className="btn primary lg" href="/register">Create your account</Link><Link className="btn outline lg" href="/login">Open MediLink</Link></div><ul className="trustRow"><li><LockKeyhole size={16}/> Role-secured access</li><li><BrainCircuit size={16}/> Explainable AI</li><li><HeartPulse size={16}/>   data</li></ul></div><div className="homeHeroVisual"><div className="floatingVital one"><HeartPulse/>72 bpm</div><div className="floatingVital two"><Watch/>Watch connected</div><div className="floatingVital three"><ShieldCheck/>Protected session</div><div className="orbitalMark"><BrandLogo compact/></div></div></section>
 <div className="homeCarouselWrap"><CareCarousel/></div>
 <section id="platform" className="section"><div className="sectionHead"><span className="eyebrow">MEDILINK PLATFORM</span><h2>A polished care experience for both sides of the consultation.</h2><p>Everything below is either functional locally or clearly labelled as a / integration.</p></div><div className="featureCards">{features.map(({icon:Icon,title,text,status})=><article className="featureCard" key={title}><div className="tileIcon"><Icon/></div><span className="status live">{status}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
 <section id="intelligence" className="section band"><div className="bandCopy"><span className="chip cyan"><BrainCircuit size={14}/> MediLink Intelligence</span><h2>Detailed AI without pretending certainty.</h2><p>Speciality routing confidence, doctor match scores and record-aware answers are deliberately separated. Model metrics are exposed so the system never implies clinical validation it does not have.</p></div><div className="bandCard"><div className="bandLine"><span>Routing model</span><strong>Calibrated  </strong></div><div className="bandLine"><span>Doctor fit</span><strong>Transparent /100 score</strong></div><div className="bandLine"><span>Copilot context</span><strong>Appointments · labs · IoT</strong></div><small>Decision-support engineering prototype. Not a diagnosis.</small></div></section>
 <section id="connected" className="section connectedBand"><div><span className="eyebrow">IOT + REMOTE CARE</span><h2>MediLink Watch brings live context into care.</h2><p>The v8 backend exposes a  wearable stream so the exact UI, APIs and alerting paths can be exercised before physical sensors are connected.</p><div className="heroButtons"><Link href="/login" className="btn primary">Open dashboard</Link><Link href="/login" className="btn outline">View Watch</Link></div></div><div className="watchMock"><Watch size={70}/><b>Connected</b><span>HR 72 · SpO₂ 98% · 36.6°C</span></div></section>
 <section id="security" className="section"><div className="cta"><ShieldCheck size={36}/><div><h2>Security is a product feature.</h2><p>Google identity verification, JWT sessions, role-based access and authenticated care-room creation are built into the experience.</p></div><Link href="/register" className="btn primary lg">Start securely</Link></div></section>
 <footer className="siteFoot"><BrandLogo/><p>Healthcare AI engineering prototype using   data. Not for clinical use. In an emergency call 999.</p></footer>
 </main>}
