"use client";
import {useEffect,useRef,useState} from "react";
import {Camera,CameraOff,Copy,Link2,LockKeyhole,Mic,MicOff,PhoneOff,Users,Video} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {API_BASE_URL,createTelehealthRoom,type TelehealthRoom} from "@/lib/api";
import {getToken} from "@/lib/auth";
import {LayoutDashboard,BrainCircuit,Watch,MessagesSquare,ShieldAlert} from "lucide-react";
const nav:NavItem[]=[{href:"/dashboard/patient",label:"Dashboard",icon:LayoutDashboard},{href:"/ai-match",label:"AI Health Assistant",icon:BrainCircuit},{href:"/video",label:"Video consultations",icon:Video},{href:"/watch",label:"MediLink Watch",icon:Watch},{href:"/messages",label:"Messages",icon:MessagesSquare},{href:"/emergency",label:"Emergency SOS",icon:ShieldAlert}];
function wsBase(){return API_BASE_URL.replace(/^http/,"ws")}
export default function VideoPage(){const local=useRef<HTMLVideoElement>(null),remote=useRef<HTMLVideoElement>(null),pc=useRef<RTCPeerConnection|null>(null),ws=useRef<WebSocket|null>(null);const [stream,setStream]=useState<MediaStream|null>(null),[mic,setMic]=useState(true),[cam,setCam]=useState(true),[room,setRoom]=useState<TelehealthRoom|null>(null),[roomId,setRoomId]=useState(""),[code,setCode]=useState(""),[status,setStatus]=useState("Ready"),[participants,setParticipants]=useState(1),[err,setErr]=useState("");
 async function media(){if(stream)return stream;const s=await navigator.mediaDevices.getUserMedia({video:true,audio:true});setStream(s);if(local.current)local.current.srcObject=s;return s}
 async function connect(rid:string,jc:string,isCreator=false){setErr("");try{const s=await media();const token=getToken();if(!token)return;const peer=new RTCPeerConnection({iceServers:[{urls:"stun:stun.l.google.com:19302"}]});pc.current=peer;s.getTracks().forEach(t=>peer.addTrack(t,s));peer.ontrack=e=>{if(remote.current)remote.current.srcObject=e.streams[0]};peer.onicecandidate=e=>{if(e.candidate&&ws.current?.readyState===1)ws.current.send(JSON.stringify({type:"ice",candidate:e.candidate}))};peer.onconnectionstatechange=()=>setStatus(peer.connectionState);const socket=new WebSocket(`${wsBase()}/api/v1/telehealth/ws/${rid}?token=${encodeURIComponent(token)}&join_code=${encodeURIComponent(jc)}`);ws.current=socket;socket.onmessage=async e=>{const m=JSON.parse(e.data);if(m.type==="presence"){setParticipants(m.participants||1);if(m.event==="peer_joined"&&isCreator){const offer=await peer.createOffer();await peer.setLocalDescription(offer);socket.send(JSON.stringify({type:"offer",sdp:offer}))}}else if(m.type==="offer"){await peer.setRemoteDescription(new RTCSessionDescription(m.sdp));const ans=await peer.createAnswer();await peer.setLocalDescription(ans);socket.send(JSON.stringify({type:"answer",sdp:ans}))}else if(m.type==="answer"){await peer.setRemoteDescription(new RTCSessionDescription(m.sdp))}else if(m.type==="ice"&&m.candidate){await peer.addIceCandidate(new RTCIceCandidate(m.candidate))}else if(m.type==="hangup"){end()}};socket.onopen=()=>setStatus("Connected to room");socket.onerror=()=>setErr("Could not connect to the secure signalling channel.");}catch(e:any){setErr(e?.message||"Camera or microphone access was not granted.")}}
 async function create(){const t=getToken();if(!t)return;const r=await createTelehealthRoom(t);setRoom(r);setRoomId(r.room_id);setCode(r.join_code);await connect(r.room_id,r.join_code,true)}
 async function join(){if(!roomId||!code)return;await connect(roomId,code,false)}
 function toggle(kind:"audio"|"video"){stream?.getTracks().filter(t=>t.kind===kind).forEach(t=>t.enabled=!t.enabled);kind==="audio"?setMic(v=>!v):setCam(v=>!v)}
 function end(){try{ws.current?.send(JSON.stringify({type:"hangup"}))}catch{};ws.current?.close();pc.current?.close();stream?.getTracks().forEach(t=>t.stop());setStream(null);setRoom(null);setParticipants(1);setStatus("Ended")}
 useEffect(()=>()=>{pc.current?.close();ws.current?.close();stream?.getTracks().forEach(t=>t.stop())},[stream]);
 return <ProtectedDashboard>{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/video" title="Secure video consultation" subtitle="Encrypted WebRTC media with authenticated MediLink signalling."><div className="videoWorkspace"><div className="videoStage dual"><video ref={remote} autoPlay playsInline className="remoteVideo"/><video ref={local} autoPlay muted playsInline className="localVideo"/>{!stream&&<div className="videoPlaceholder"><Camera size={44}/><h2>Start or join a consultation</h2><p>Create a care room, or enter a room ID and join code shared by your care team.</p><div className="joinGrid"><button className="btn primary" onClick={create}>Create secure room</button><span>or</span><input value={roomId} onChange={e=>setRoomId(e.target.value)} placeholder="Room ID"/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="Join code"/><button className="btn outline" onClick={join}>Join room</button></div></div>}{stream&&<div className="callControls"><button onClick={()=>toggle("video")}>{cam?<Camera/>:<CameraOff/>}</button><button onClick={()=>toggle("audio")}>{mic?<Mic/>:<MicOff/>}</button><button className="hangup" onClick={end}><PhoneOff/></button></div>}</div><aside className="callSide"><div className="secureCallTag"><LockKeyhole/> Secure care session</div><h2>Consultation room</h2><div className="callStatus"><Users size={16}/><span>{participants} participant{participants===1?"":"s"}</span><em>{status}</em></div>{room&&<><label>Room ID</label><div className="copyCode"><code>{room.room_id}</code><button onClick={()=>navigator.clipboard?.writeText(room.room_id)}><Copy size={15}/></button></div><label>Join code</label><div className="copyCode"><code>{room.join_code}</code><button onClick={()=>navigator.clipboard?.writeText(room.join_code)}><Copy size={15}/></button></div></>}{err&&<p className="formError">{err}</p>}<div className="callChecklist"><span>✓ Account authenticated</span><span>✓ WebRTC encrypted media</span><span>✓ Authenticated signalling channel</span><span>✓ Camera and microphone controlled by your browser</span><span>• TURN can be added for production-grade NAT traversal</span></div></aside></div></AppShell>}</ProtectedDashboard>}
