"use client";
import {useEffect,useState} from "react";
import {Boxes,Database,HardDrive,Network,RefreshCw,ServerCog} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {getPlatformStatus,createPlatformJob,type PlatformStatus} from "@/lib/api";
import {getToken} from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/admin",label:"Operations",icon:Boxes},{href:"/platform",label:"Platform",icon:ServerCog},{href:"/intelligence",label:"Intelligence",icon:Network},{href:"/network",label:"Care network",icon:Database}];
export default function Platform(){const [data,setData]=useState<PlatformStatus|null>(null);const [job,setJob]=useState<any>(null);useEffect(()=>{const t=getToken();if(t)getPlatformStatus(t).then(setData)},[]);async function run(){const t=getToken();if(t)setJob(await createPlatformJob(t,"record_index_refresh","Refresh searchable record index"));}return <ProtectedDashboard requiredRole="admin">{(u,l)=><AppShell user={u} logout={l} nav={nav} active="/platform" title="Platform control" subtitle="Data, interoperability, background processing and service health."><div className="opsStats"><article><Database/><b>{data?.database?.configured||"…"}</b><span>Database</span></article><article><RefreshCw/><b>{data?.cache?.provider||"…"}</b><span>Cache</span></article><article><HardDrive/><b>{data?.object_storage?.provider||"…"}</b><span>Object storage</span></article><article><Network/><b>FHIR R4</b><span>Interoperability</span></article></div><div className="grid"><section className="card span2"><div className="cardTop"><h2>Production architecture</h2><ServerCog size={18}/></div><div className="miniList"><div><span>Migration layer</span><b>Alembic ready</b></div><div><span>Background jobs</span><b>{data?.jobs?.enabled?"Enabled":"Disabled"}</b></div><div><span>FHIR base</span><b>{data?.interoperability?.base||"/api/v1/fhir"}</b></div><div><span>Local fallback</span><b>SQLite + filesystem</b></div></div></section><section className="card"><h2>Job worker</h2><p>Queue long-running indexing, document and analytics tasks outside the request path.</p><button className="primaryButton" onClick={run}>Run index refresh</button>{job&&<div className="successBox">{job.job_type}: {job.status} · {job.progress}%</div>}</section></div></AppShell>}</ProtectedDashboard>}
