"use client";
import {useEffect,useState} from "react";
import {Activity,BatteryCharging,Bluetooth,LayoutDashboard,MessagesSquare,ShieldAlert,Video,Watch,Wifi,TriangleAlert} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import LiveVitals from "@/components/LiveVitals";
import {getLiveVitals,type LiveVitalsResponse} from "@/lib/api";
import {getToken} from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/patient",label:"Dashboard",icon:LayoutDashboard},{href:"/watch",label:"MediLink Watch",icon:Watch,badge:"Live"},{href:"/video",label:"Video consultations",icon:Video},{href:"/messages",label:"Messages",icon:MessagesSquare},{href:"/emergency",label:"Emergency SOS",icon:ShieldAlert}];
export default function WatchPage(){const [v,setV]=useState<LiveVitalsResponse|null>(null);useEffect(()=>{const t=getToken();if(!t)return;const load=()=>getLiveVitals(t).then(setV).catch(()=>{});load();const id=setInterval(load,4000);return()=>clearInterval(id)},[]);return <ProtectedDashboard>{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/watch" title="MediLink Watch" subtitle="A connected-health workspace for live vitals, trends and monitoring alerts."><div className="watchHero"><div><span className="eyebrow"><Watch size={14}/> CONNECTED</span><h2>Your health signals, in motion.</h2><p>MediLink Watch streams encrypted observations through the IoT gateway so trends can be viewed by you and, where authorised, your care team.</p></div><div className="watchDevice"><Watch/><div><b>MediLink Watch</b><span><i/>Connected now</span></div><strong>{v?.battery??84}%</strong></div></div><div className="grid"><section className="card span2"><LiveVitals/></section><section className="card"><div className="cardTop"><h2>Monitoring status</h2><Activity size={18}/></div><div className={`monitorStatus ${v?.status??"stable"}`}><span>{v?.status==="attention"?<TriangleAlert/>:<Activity/>}</span><div><b>{v?.status==="attention"?"Review recommended":"All monitored signals stable"}</b><p>{v?.anomalies?.length?`${v.anomalies.length} monitoring signal(s) crossed a configured threshold.`:"No threshold alerts are active right now."}</p></div></div><div className="deviceDetails"><span><BatteryCharging/> Battery <b>{v?.battery??84}%</b></span><span><Wifi/> Gateway <b>Secure</b></span><span><Bluetooth/> Device link <b>Connected</b></span></div></section><section className="card span3"><div className="cardTop"><h2>Recent monitoring alerts</h2><TriangleAlert size={18}/></div>{v?.anomalies?.length?<div className="anomalyList">{v.anomalies.map(a=><article key={a.code}><span className={`severity ${a.severity}`}>{a.severity}</span><div><b>{a.title}</b><p>{a.detail}</p></div><time>{new Date(a.observed_at).toLocaleTimeString()}</time></article>)}</div>:<div className="emptyState"><Activity size={24}/><p>No active monitoring alerts.</p></div>}</section></div></AppShell>}</ProtectedDashboard>}
