"use client";
import { useEffect,useState } from "react";
import { FileHeart, FlaskConical, LayoutDashboard, Pill, Watch } from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import { getPatientSnapshot,type PatientSnapshot } from "@/lib/api";
import { getToken } from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/patient",label:"Dashboard",icon:LayoutDashboard},{href:"/records",label:"My health records",icon:FileHeart},{href:"/watch",label:"MediLink Watch",icon:Watch}];
export default function Records(){const [s,setS]=useState<PatientSnapshot|null>(null);useEffect(()=>{const t=getToken();if(t)getPatientSnapshot(t).then(setS)},[]);return <ProtectedDashboard requiredRole="patient">{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/records" title="My health record" subtitle="A longitudinal  record designed around clear provenance and patient-friendly summaries."><div className="grid"><section className="card span2"><div className="cardTop"><h2>Laboratory results</h2><FlaskConical/></div><div className="miniList labs">{s?.labs.map(l=><div key={l.name}><span><b>{l.name}</b><small>{l.date} · {l.reference}</small></span><em className={l.status}>{l.value}</em></div>)}</div></section><section className="card"><div className="cardTop"><h2>Medication list</h2><Pill/></div><div className="miniList">{s?.medications.map(m=><div key={m.name}><span><b>{m.name}</b><small>{m.dose} · {m.schedule}</small></span><em>{m.next_due}</em></div>)}</div></section><section className="card span3"><h2>Timeline</h2><div className="timelineV8"><div><i/><b>2 Oct 2026</b><span>Complete Blood Count imported.</span></div><div><i/><b>28 Sep 2026</b><span>Routine blood tests added.</span></div><div><i/><b>21 Sep 2026</b><span>Medication list updated.</span></div><div><i/><b>4 Sep 2026</b><span>General medicine encounter recorded.</span></div></div></section></div></AppShell>}</ProtectedDashboard>}
