"use client";
import {useEffect,useState} from "react";
import {Activity,BarChart3,BedDouble,CalendarDays,FileCheck2,FileClock,LayoutDashboard,Stethoscope,Users,UserRoundCog} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {getAdminOverview,type OpsSummary} from "@/lib/api";
import {getToken} from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/admin",label:"Operations",icon:LayoutDashboard},{href:"/dashboard/admin#capacity",label:"Capacity",icon:BedDouble},{href:"/dashboard/admin#departments",label:"Departments",icon:Stethoscope},{href:"/dashboard/admin#activity",label:"Activity",icon:Activity},{href:"/audit",label:"Audit history",icon:FileClock}];
export default function AdminDashboard(){const [data,setData]=useState<OpsSummary|null>(null);useEffect(()=>{const t=getToken();if(t)getAdminOverview(t).then(setData).catch(()=>{})},[]);const d=data;return <ProtectedDashboard requiredRole="admin">{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/dashboard/admin" title="Hospital operations" subtitle="A live operational view across people, appointments, clinical documentation and capacity."><div className="opsHero"><div><span className="eyebrow"><BarChart3 size={14}/> OPERATIONS CENTRE</span><h2>One view of the care network.</h2><p>Monitor service demand, clinical capacity and patient-flow signals without leaving MediLink.</p></div><div className="opsPulse"><span><i/>Services online</span><strong>{d?.occupancy??78}%</strong><small>Current occupancy</small></div></div><div className="commandRibbon"><span><i className="liveDot"/> Care network online</span><b>Flow intelligence · Clinical activity · Capacity · Governance</b></div><div className="opsStats"><article><Users/><b>{d?.patients??1284}</b><span>Patients</span></article><article><UserRoundCog/><b>{d?.clinicians??86}</b><span>Clinicians</span></article><article><CalendarDays/><b>{d?.appointments??312}</b><span>Appointments</span></article><article><FileCheck2/><b>{d?.signed_notes??274}</b><span>Signed notes</span></article></div><div className="grid"><section className="card span2" id="departments"><div className="cardTop"><h2>Department load</h2><Stethoscope size={18}/></div><div className="departmentList">{(d?.departments??[]).map(x=><div key={x.name}><div><b>{x.name}</b><span>{x.clinicians} clinicians · {x.waiting} waiting</span></div><div className="loadBar"><i style={{width:`${x.load}%`}}/></div><strong>{x.load}%</strong></div>)}</div></section><section className="card" id="capacity"><div className="cardTop"><h2>Capacity</h2><BedDouble size={18}/></div><div className="capacityRing"><strong>{d?.occupancy??78}%</strong><span>Occupancy</span></div><div className="miniList"><div><span>Waiting room</span><b>{d?.waiting_room??11}</b></div><div><span>Open appointment slots</span><b>{d?.open_slots??148}</b></div><div><span>Active users</span><b>{d?.active_users??421}</b></div></div></section><section className="card span3"><div className="cardTop"><h2>Patient flow pulse</h2><BarChart3 size={18}/></div><div className="flowChart">{[42,58,51,68,74,63,79,72,84,76,69,81].map((v,i)=><i key={i} style={{height:`${v}%`}} title={`${v}%`}/>)}</div><div className="flowLegend"><span>06:00</span><span>12:00</span><span>18:00</span><span>Now</span></div></section><section className="card span3" id="activity"><div className="cardTop"><h2>Operational activity</h2><Activity size={18}/></div><div className="activityFeed">{(d?.recent_activity??[]).map(x=><article key={x.time+x.title}><time>{x.time}</time><i/><div><b>{x.title}</b><p>{x.detail}</p></div></article>)}</div></section></div></AppShell>}</ProtectedDashboard>}
