"use client";
import {useEffect,useState} from "react";
import {Activity,HeartPulse,Radio,Video,Watch} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {getConnectedDevices,getVitalsHistory,getConnectedNetwork} from "@/lib/api";
import {getToken} from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/patient",label:"Dashboard",icon:Activity},{href:"/watch",label:"Watch",icon:Watch},{href:"/connected-care",label:"Connected care",icon:Radio},{href:"/video",label:"Video care",icon:Video}];
export default function ConnectedCare(){const [devices,setDevices]=useState<any[]>([]);const [history,setHistory]=useState<any[]>([]);const [network,setNetwork]=useState<any>(null);useEffect(()=>{const t=getToken();if(t){getConnectedDevices(t).then(setDevices);getVitalsHistory(t).then(setHistory);getConnectedNetwork(t).then(setNetwork)}},[]);return <ProtectedDashboard>{(u,l)=><AppShell user={u} logout={l} nav={nav} active="/connected-care" title="Connected care" subtitle="Devices, remote monitoring and telehealth network status."><div className="grid"><section className="card span2"><div className="cardTop"><h2>Connected devices</h2><Watch size={18}/></div><div className="deviceGrid">{devices.map(d=><article key={d.id}><Watch/><div><b>{d.name}</b><span>{d.transport}</span></div><strong>{d.battery}%</strong><em>{d.status}</em></article>)}</div></section><section className="card"><h2>Care network</h2><div className="miniList"><div><span>MQTT</span><b>{network?.mqtt?.status||"…"}</b></div><div><span>WebRTC</span><b>{network?.webrtc?.turn||"…"}</b></div><div><span>Stream latency</span><b>{network?.stream_processing?.latency_ms||"—"} ms</b></div></div></section><section className="card span3"><div className="cardTop"><h2>24-hour vitals trend</h2><HeartPulse size={18}/></div><div className="vitalsHistory">{history.slice(-18).map((x,i)=><i key={i} style={{height:`${Math.max(16,Math.min(96,(x.heart_rate-45)*2))}%`}} title={`${x.heart_rate} bpm · SpO₂ ${x.spo2}%`}/>)}</div></section></div></AppShell>}</ProtectedDashboard>}
