"use client";
import {useEffect,useMemo,useState} from "react";
import {useSearchParams} from "next/navigation";
import {ClipboardCheck,FileHeart,LayoutDashboard,MessagesSquare,Search,Users,Video,Watch,Save,CheckCircle2} from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import {createClinicalNote,getClinicalPatients,getPatientNotes,getPatientRecord,updateClinicalNote,type ClinicalNote,type ClinicalPatient,type RecordItem} from "@/lib/api";
import {getToken} from "@/lib/auth";
const nav:NavItem[]=[{href:"/dashboard/doctor",label:"Clinical dashboard",icon:LayoutDashboard},{href:"/patients",label:"Patient records",icon:Users},{href:"/video",label:"Video consultations",icon:Video},{href:"/messages",label:"Secure messages",icon:MessagesSquare},{href:"/watch",label:"Remote monitoring",icon:Watch}];
export default function Patients(){const params=useSearchParams();const [patients,setPatients]=useState<ClinicalPatient[]>([]);const [selected,setSelected]=useState<number|null>(null);const [records,setRecords]=useState<RecordItem[]>([]);const [notes,setNotes]=useState<ClinicalNote[]>([]);const [q,setQ]=useState("");const [form,setForm]=useState({subjective:"",objective:"",assessment:"",plan:""});const [saved,setSaved]=useState("");
 useEffect(()=>{const t=getToken();if(!t)return;getClinicalPatients(t).then(ps=>{setPatients(ps);const requested=Number(params.get("patient"));setSelected(requested||ps[0]?.patient_id||null)}).catch(()=>{});},[params]);
 useEffect(()=>{const t=getToken();if(!t||!selected)return;Promise.all([getPatientRecord(t,selected),getPatientNotes(t,selected)]).then(([r,n])=>{setRecords(r);setNotes(n)}).catch(()=>{});},[selected]);
 const current=patients.find(p=>p.patient_id===selected);const filtered=useMemo(()=>patients.filter(p=>p.full_name.toLowerCase().includes(q.toLowerCase())),[patients,q]);
 async function saveNote(){const t=getToken();if(!t||!selected)return;const note=await createClinicalNote(t,{patient_id:selected,...form});setNotes(n=>[note,...n]);setSaved("Draft saved");setTimeout(()=>setSaved(""),1800)}
 async function signNote(n:ClinicalNote){const t=getToken();if(!t)return;const updated=await updateClinicalNote(t,n.id,{status:"signed"});setNotes(x=>x.map(v=>v.id===updated.id?updated:v));}
 return <ProtectedDashboard requiredRole="doctor">{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/patients" title="Patient records" subtitle="Review longitudinal context, connected monitoring and clinical documentation in one place."><div className="recordsWorkspace"><aside className="patientSidebar"><div className="recordSearch"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search patients"/></div>{filtered.length?filtered.map(p=><button key={p.patient_id} className={`patientListItem ${selected===p.patient_id?"active":""}`} onClick={()=>setSelected(p.patient_id)}><span className="avatar patient">{p.full_name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span><b>{p.full_name}</b><small>{p.latest_reason||"Care review"}</small></span></button>):<div className="emptyState"><small>No linked patients yet.</small></div>}</aside>
 <main className="recordMain">{current?<><section className="patientBanner"><div className="avatar patient large">{current.full_name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><span className="eyebrow">ACTIVE CARE RECORD</span><h2>{current.full_name}</h2><p>{current.email} · {current.record_items} record items · {current.upcoming_appointments} upcoming appointment(s)</p></div><button className="btn outline"><Video size={15}/> Start call</button></section>
 <div className="recordGrid"><section className="card"><div className="cardTop"><h2>Timeline</h2><FileHeart size={18}/></div><div className="timelineRich">{records.map((r,i)=><article key={`${r.title}-${i}`}><i/><div><small>{new Date(r.created_at).toLocaleDateString()}</small><b>{r.title}</b><span>{r.record_type}</span><p>{r.body}</p></div></article>)}</div></section>
 <section className="card noteComposer"><div className="cardTop"><h2>Clinical note</h2>{saved&&<span className="successText"><CheckCircle2 size={14}/>{saved}</span>}</div>{(["subjective","objective","assessment","plan"] as const).map(k=><label key={k}><span>{k[0].toUpperCase()+k.slice(1)}</span><textarea value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={`Add ${k}…`}/></label>)}<button className="btn primary" onClick={saveNote}><Save size={15}/> Save draft</button></section></div>
 <section className="card"><div className="cardTop"><h2>Clinical documentation</h2><ClipboardCheck size={18}/></div>{notes.length?<div className="notesList">{notes.map(n=><article key={n.id}><div><span className={`statusDot ${n.status}`}/><b>{n.note_type} note</b><small>{new Date(n.updated_at).toLocaleString()} · {n.status}</small></div><p><strong>A:</strong> {n.assessment||"No assessment entered"}</p>{n.status!=="signed"&&<button className="btn small outline" onClick={()=>signNote(n)}>Sign note</button>}</article>)}</div>:<p className="muted">No saved clinical notes yet.</p>}</section></>:<div className="emptyState"><Users size={30}/><p>Select a patient to open the clinical record.</p></div>}</main></div></AppShell>}</ProtectedDashboard>}
