"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { CalendarDays,ClipboardPlus,FileHeart,LayoutDashboard,MessagesSquare,ShieldAlert,Users,Video,Watch,Stethoscope,ChevronRight,Route,Building2,Settings2 } from "lucide-react";
import ProtectedDashboard from "@/components/ProtectedDashboard";
import AppShell,{type NavItem} from "@/components/AppShell";
import LiveVitals from "@/components/LiveVitals";
import AICopilotPanel from "@/components/AICopilotPanel";
import {getDoctorSnapshot,getMyAppointments,getClinicalPatients,type Appointment,type DoctorSnapshot,type ClinicalPatient} from "@/lib/api";
import {getToken} from "@/lib/auth";
import {fmtDateTime,greeting} from "@/lib/format";
const nav:NavItem[]=[{href:"/dashboard/doctor",label:"Clinical dashboard",icon:LayoutDashboard},{href:"/patients",label:"Patient records",icon:FileHeart},{href:"/clinical-actions",label:"Care actions",icon:ClipboardPlus,badge:"New"},{href:"/video",label:"Video consultations",icon:Video},{href:"/messages",label:"Secure messages",icon:MessagesSquare},{href:"/watch",label:"Remote monitoring",icon:Watch,badge:"Live"},{href:"/dashboard/doctor#alerts",label:"Clinical alerts",icon:ShieldAlert},{href:"/patients",label:"Clinical notes",icon:ClipboardPlus},{href:"/referrals",label:"Referrals",icon:Route},{href:"/hospitals",label:"Care network",icon:Building2},{href:"/settings",label:"Settings",icon:Settings2}];
export default function DoctorDashboard(){const [appointments,setAppointments]=useState<Appointment[]>([]);const [snapshot,setSnapshot]=useState<DoctorSnapshot|null>(null);const [patients,setPatients]=useState<ClinicalPatient[]>([]);useEffect(()=>{const t=getToken();if(!t)return;Promise.all([getMyAppointments(t),getDoctorSnapshot(t),getClinicalPatients(t)]).then(([a,s,p])=>{setAppointments(a);setSnapshot(s);setPatients(p)}).catch(()=>{});},[]);const queue=appointments.filter(a=>a.status==="scheduled").sort((a,b)=>+new Date(a.scheduled_at)-+new Date(b.scheduled_at));return <ProtectedDashboard requiredRole="doctor">{(user,logout)=><AppShell user={user} logout={logout} nav={nav} active="/dashboard/doctor" title={<>{greeting()}, {user.full_name}.</>} subtitle="Your clinical command centre for consultations, patient records, monitoring and documentation." actions={<><Link href="/video" className="btn outline"><Video size={16}/> Start care room</Link><Link href="/clinical-actions" className="btn outline"><ClipboardPlus size={16}/> Care actions</Link><Link href="/patients" className="btn primary"><Users size={16}/> Patient records</Link></>}>
<div className="doctorHero"><div><span className="eyebrow"><Stethoscope size={14}/> CLINICAL WORKSPACE</span><h2>Everything you need for the next decision.</h2><p>Move from queue to record, monitoring, notes and secure consultation without losing clinical context.</p></div><div className="doctorHeroStats"><div><b>{queue.length}</b><span>Upcoming</span></div><div><b>{patients.length||3}</b><span>Patients</span></div><div><b>{snapshot?.messages??6}</b><span>Messages</span></div></div></div>
<div className="grid v8Grid"><section className="card span2" id="queue"><div className="cardTop"><h2>Patient queue</h2><CalendarDays size={18}/></div>{queue.length?<div className="queueCards">{queue.slice(0,5).map((a,i)=><div className={`queueCard ${i===0?"next":""}`} key={a.id}><div><span>{fmtDateTime(a.scheduled_at)}</span><b>{a.patient_name}</b><small>{a.reason}</small></div><div className="inlineActions"><Link href={`/patients?patient=${a.patient_id}`} className="btn small outline"><FileHeart size={14}/> Record</Link><Link href="/video" className="btn small primary"><Video size={14}/> Join</Link></div></div>)}</div>:<div className="emptyState"><p>No upcoming appointments are currently queued.</p><Link href="/patients" className="btn outline">Open patient records</Link></div>}</section><AICopilotPanel role="doctor"/>
<section className="card span2"><LiveVitals/></section><section className="card" id="alerts"><div className="cardTop"><h2>Clinical alerts</h2><ShieldAlert size={18}/></div><div className="miniList alerts">{(snapshot?.alerts??[]).map(a=><div key={a.patient+a.signal}><span><b>{a.patient}</b><small>{a.signal} · {a.detail}</small></span><em className={a.severity}>{a.severity}</em></div>)}</div></section>
<section className="card span2"><div className="cardTop"><h2>Recently active patients</h2><Link href="/patients" className="textLink">View all <ChevronRight size={14}/></Link></div><div className="patientDirectory">{(patients.length?patients:[{patient_id:1,full_name:"Sample Patient",email:"patient@medilink.health",upcoming_appointments:1,record_items:4,latest_reason:"General medicine review"}]).slice(0,4).map(p=><Link href={`/patients?patient=${p.patient_id}`} className="patientTile" key={p.patient_id}><div className="avatar patient">{p.full_name.split(" ").map(x=>x[0]).join("").slice(0,2)}</div><div><b>{p.full_name}</b><span>{p.latest_reason||"Care review"}</span><small>{p.record_items} record items · {p.upcoming_appointments} upcoming</small></div><ChevronRight size={17}/></Link>)}</div></section>
<section className="card"><div className="cardTop"><h2>Worklist</h2><ClipboardPlus size={18}/></div><div className="worklist"><div><strong>{snapshot?.notes_to_review??3}</strong><span>Notes to review</span></div><div><strong>{snapshot?.results_to_review??4}</strong><span>Results to review</span></div><div><strong>{snapshot?.messages??6}</strong><span>Messages</span></div></div></section></div></AppShell>}</ProtectedDashboard>}
